/* XPM */
static xpm_row_t const mouse_cursor_xpm[] = {
/* columns rows colors chars-per-pixel */
"15 26 17 1 ",
"  c None",
". c #000000",
"X c #010000",
"o c #000100",
"O c #000001",
"+ c #000000",
"@ c #000000",
"# c #A6A6A7",
"$ c #A8AAA8",
"% c #000000",
"& c #ADAEAD",
"* c #B2B3B3",
"= c #000000",
"- c #FFFFFE",
"; c #FFFEFF",
": c #FEFFFF",
"> c #FFFFFF",
/* pixels */
"O              ",
"OOO            ",
"O;=O           ",
"O;=O           ",
"O;;;O          ",
"O;;;;O         ",
"O;;;;;OO       ",
"O;;;;;;&O      ",
"O;;-;;-&O      ",
"O;;;;;;;;O     ",
"O;;;;;;;;;O    ",
"O;:-;;;;;;;O   ",
"O;;;;;;;;;;;@O ",
"O;;;;;;;;;;;@O ",
"O;;;;;;;;OOOOOO",
"O;;;;O;;;O     ",
"O;;;OO;;;O     ",
"O;=O  O$;;O    ",
"O;=O  O$;;O    ",
"OOO   O$;;O    ",
"O       O;;O   ",
"        O;;O   ",
"         O;;@O ",
"         O;;@O ",
"         O;;@O ",
"          OO   "
};
