/* XPM */
static xpm_row_t const red_car_xpm[] = {
/* columns rows colors chars-per-pixel */
"260 100 220 2 ",
"   c None",
".  c #15151B",
"X  c #19191E",
"o  c #121217",
"O  c #1C1C23",
"+  c #1F1F28",
"@  c #2B1F27",
"#  c #341E26",
"$  c #3A1C23",
"%  c #1F2A34",
"&  c #1F2732",
"*  c #222225",
"=  c #23232D",
"-  c #2B222B",
";  c #2B2B2D",
":  c #2F2027",
">  c #33242C",
",  c #382229",
"<  c #262631",
"1  c #2C2732",
"2  c #252B35",
"3  c #2A2A34",
"4  c #2D2D38",
"5  c #322730",
"6  c #323234",
"7  c #34333B",
"8  c #3A3A3C",
"9  c #38363F",
"0  c #2C353F",
"q  c #4C171D",
"w  c #57171B",
"e  c #6C1215",
"r  c #631A1F",
"t  c #661519",
"y  c #731214",
"u  c #7D1012",
"i  c #7D1518",
"p  c #77181B",
"a  c #421A20",
"s  c #4F1F26",
"d  c #5A1C21",
"f  c #741E20",
"g  c #452129",
"h  c #5B292E",
"j  c #63262B",
"k  c #3B3A43",
"l  c #383740",
"z  c #423D46",
"x  c #434344",
"c  c #4C4C4C",
"v  c #48454B",
"b  c #545454",
"n  c #5B5B5B",
"m  c #6B6B6A",
"M  c #656564",
"N  c #747473",
"B  c #797978",
"V  c #8D0E0F",
"C  c #9B0404",
"Z  c #930E0F",
"A  c #9B0909",
"S  c #960303",
"D  c #860F11",
"F  c #821416",
"G  c #8A1215",
"H  c #801518",
"J  c #931113",
"K  c #9D1112",
"L  c #9A1C1E",
"P  c #A30A0A",
"I  c #AB0B0B",
"U  c #A40505",
"Y  c #B30A0B",
"T  c #BC0A0A",
"R  c #BA0606",
"E  c #A40F11",
"W  c #A80F10",
"Q  c #A21313",
"!  c #A31B1B",
"~  c #AC1818",
"^  c #B91717",
"/  c #BB3503",
"(  c #BD3A05",
")  c #BB3B0B",
"_  c #B73609",
"`  c #BC3F11",
"'  c #B43D10",
"]  c #B82E03",
"[  c #992626",
"{  c #8B2528",
"}  c #B82727",
"|  c #B02B2B",
" . c #CB0606",
".. c #C30B0B",
"X. c #CC0B0B",
"o. c #C60606",
"O. c #D30404",
"+. c #D80101",
"@. c #D10B0B",
"#. c #DA0A09",
"$. c #D00807",
"%. c #CE1414",
"&. c #C51717",
"*. c #D21C1C",
"=. c #D01414",
"-. c #E20909",
";. c #EB0908",
":. c #E80505",
">. c #F30909",
",. c #FE0907",
"<. c #C03603",
"1. c #C13B05",
"2. c #C13E0B",
"3. c #C03F11",
"4. c #C22B2B",
"5. c #D22222",
"6. c #D82E2E",
"7. c #D13232",
"8. c #F62222",
"9. c #BD4309",
"0. c #BC4214",
"q. c #BD451C",
"w. c #B8481B",
"e. c #BC4B23",
"r. c #B94C26",
"t. c #BD522C",
"y. c #BC552A",
"u. c #BD5634",
"i. c #BB5838",
"p. c #BE603F",
"a. c #C44405",
"s. c #C64A04",
"d. c #CB4C04",
"f. c #CA4D08",
"g. c #CD5206",
"h. c #CE5807",
"j. c #D25606",
"k. c #D35B06",
"l. c #D55908",
"z. c #C24812",
"x. c #CD4F0A",
"c. c #D46305",
"v. c #D96406",
"b. c #D56B05",
"n. c #DB6A06",
"m. c #D77305",
"M. c #DB7405",
"N. c #DD7C05",
"B. c #CE6104",
"V. c #E37E06",
"C. c #E26A08",
"Z. c #C14C24",
"A. c #C04E2C",
"S. c #C3522C",
"D. c #C55826",
"F. c #C45B3A",
"G. c #C45834",
"H. c #C36023",
"J. c #BC6344",
"K. c #BB6F54",
"L. c #CF5244",
"P. c #C66545",
"I. c #D7785D",
"U. c #DE8205",
"Y. c #DF8905",
"T. c #E48B05",
"R. c #E98C05",
"E. c #E28405",
"W. c #EA9405",
"Q. c #EC9B04",
"!. c #E59605",
"~. c #F29E05",
"^. c #EBA503",
"/. c #EEAA03",
"(. c #F2A504",
"). c #F2AC04",
"_. c #FCAF05",
"`. c #F2B204",
"'. c #737685",
"]. c #727689",
"[. c #757A8D",
"{. c #797E93",
"}. c #767B90",
"|. c #7C8197",
" X c #8D8D8B",
".X c #858584",
"XX c #84899F",
"oX c #81869B",
"OX c #989897",
"+X c #A1A19E",
"@X c #868BA2",
"#X c #898FA4",
"$X c #8D91A5",
"%X c #8F94A8",
"&X c #9196A9",
"*X c #959AAC",
"=X c #999DAD",
"-X c #9EA1AF",
";X c #9FA3B0",
":X c #AEAEAE",
">X c #A4A5AA",
",X c #A2A5B0",
"<X c #A5A8B1",
"1X c #ACADB2",
"2X c #AFB0B2",
"3X c #B2B2B1",
"4X c #BCBCBB",
"5X c #B7B7B8",
"6X c #B0B0AF",
"7X c #C2C2BF",
"8X c #BFBFC1",
"9X c #C2C2C2",
"0X c #CCCCCC",
"qX c #C8C8C6",
"wX c #D4D4D3",
"eX c #DBDBDA",
"rX c #D0D0CE",
"tX c #E0E0DD",
"yX c #E2E2E1",
"uX c #EAEAE8",
/* pixels */
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                      5.*.X.X.X.X.X.X.%.*.*.*.5.5.%.*.5.6.L.                                                                                                                                                                            ",
"                                                                                                                                                                                                                                                                                                                5.@. .X. .X.X.X.X.X.X.$.X. . . .X.X. . . . . .X.X.X. . .X.X.X.@.X.X.*.*.                                                                                                                                                ",
"                                                                                                                                                                                                                                                                                                            *.X. .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X. .X.%.                                                                                                                                            ",
"                                                                                                                                                                                                                                                                                                        *.%. . .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X. .X.*.                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                      X.X.X.X.X.X.X.X.X.X.X.X.X.X.$.X.$.@. .$.X. .@. .@. .@.X.$.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.*.                                                                                                                                      ",
"                                                                                                                                                                                                                                                                                                  %.X.X.X.X.X.X.X.X.X.X.X.X.$.+.+.$.O.$.$.$.$.$.$.$.$.$.O.O.$.O.+.+.$.X.X.X.X.X.X.X.X.X.O.O.+.+.+.=.                                                                                                                                    ",
"                                                                                                                                                                                                                                                                                              %. .X.X.X.X.X.X.X.X.X.X.X.X.+...                                      { O.O.X.X.X.X.X.X.$.~         @.X.                                                                                                                                  ",
"                                                                                                                                                                                                                                                                                          X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.O.                                              X.O.X.X.X.X.O.~             X.X.                                                                                                                                ",
"                                                                                                                                                                                                                                                                                    5.%.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.O.                                                  ^ O.X.X.X.O.{               X.X.                                                                                                                              ",
"                                                                                                                                                                                                                                                                                *.%. .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.+.                                                      ^ O.X.X.X.X.                X.X.                                                                                                                            ",
"                                                                                                                                                                                                                                                                            *.X. .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.O.^                                                         @.O.X.X.O.L               X.X.                                                                                                                            ",
"                                                                                                                                                                                                                                                                      5.%.X. .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.+.                                                            $.X.X.X.+.                X.X.                                                                                                                          ",
"                                                                                                                                                                                                                                                                *.*.X. . .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.+.                                                                +.X.X.@.O.                X.X.                                                                                                                        ",
"                                                                                                                                                                                                                                                          *.=.X.X.X.$.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.$...                                                                [ +.X.X.$.T                 X.X.                                                                                                                      ",
"                                                                                                                                                                                                                                                6.*.=.$.$.$.$.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.O.                                                                    @. .X.X.O.                  X.X.                                                                                                                    ",
"                                                                                                                                                                                                                                    7.&.&.&.....o.o...........X.X.X.@.@.@.X.@.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.$.                                                                        +.X.X.X.+.                  X.X.                                                                                                                  ",
"                                                                                                                                                                                                          ! K Q Q Q Q Q Q P A C C A C C C A A A A A P A A A A A P I I Y R T ..X.X.X.@.@.@.X.X.@.X.X.X.X.X.X.+.                                                                        ! +.X.X.@.$.                X.X.X.                                                                                                                ",
"                                                                                                                                                                                                      ! C S A C C S C C C A A A A A A A A A A A A A A A A A A A A A A A A A A A P I I Y T T ..X.X.@.@.@.X.X.O.                                                                          $.X.X.X.$.!                 X.X.X.                                                                                                              ",
"                                                                                                                                                                                                    Q S A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A P P I Y T ..X...                                                                          +.X.X.X.+.                    X.X.                                                                                                            ",
"                                                                                                                                                                                                  ! S A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A U I                                                                         X.X.X.X.X.O.                    ..Y A E A K Q K Q Q Q Q K ! Q Q Q ! ! ! | ! |                                                                 ",
"                                                                                                                                                                                                  C A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A C A A A A A A A A A A A A A A A A A A A A A A A A C U C U A H                                                               +.X.X.X.@.T                   I P A A A A A A C C A A C A A C C C C C S S C C A Q ~ }                                                       ",
"                                                                                                                                  P.G.S.e.q.0.` 0.3.` ` 0.q.e.S.F.                              | A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A C A A A A A A A P C C C C U C C A F p                                               &.$.X.X.X.O.                C C A A A A A A A A A A A A A A A A A A A A A A A C S S C A ~ }                                                 ",
"                                                                                                                              r._ / / / ( ( 1.<.<.<.<.<.<.<.<.1.2.q.G.                          ! C A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A C A C P C C C C C C U A G p                                   #.X.X.X.X.+.            C U A A A A A A A A A A A A A A A A A A A A A A A A A A A A A C C Q                                               ",
"                                                                                        t.w.0.9.9.z.2.9.0.q.Z.t.i.P.            I.Z.1.1.<.1.1.2.2.a.a.a.1.1.1.( <./ / ) G.                      ! C P A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A P A A A A A A A A A A A A A A A A A A A A C U C C C C C G f                     &.+.@.@.@.@.$.        C A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A C C ~                                           ",
"                                                                                        F.G.q.0.s.s.j.l.l.s.a.1.9.( ) 0.0.Z.A.i.P.S.( 1.x.j.j.j.l.l.k.k.k.k.g.g.f.a.1.( ( 0.                    *. .......T T Y Y Y I I I P P P P A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A C A A A A A A A A A A A C U C U C A H         [ R T ....X.O.[     S A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A C C 4.                                      ",
"                                                                                                  A.Z.f.h.M.V.V.n.v.c.h.g.s.d.a.9.a.a.s.c.n.b.b.b.b.b.b.b.b.b.c.c.l.g.a.2.<.) F.                *. .@.@.@.@.@.@.@.@.@.@.@.@.X.X.X.........T R Y Y Y I I I P P P P A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A C A A A A A A A A U C C C U C A A A A P P I I C C A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A C ^                                     ",
"                                                                                                          D.b.~._.).^.Q.Q.Q.W.R.R.T.T.T.W.W.!.Q.^.~.Q.Q.^.!.!.T.N.M.c.k.g.1./ _ P.              *.$.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.@.X.@.X.@.@.@.@.@.X.@.X.X.X.X.........T R Y Y I I I I P P P A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A C A A C C A A A A A A A C A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A S ^                                   ",
"                                                                                                          t./ s.V.^.^./././.^./.).`.^./././.^././.^.)././.^.^.^._.(.T.M.c.j.a.( )               *. .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.X.X.@.X.X.@.X.X.X.@.X.X.X.........T Y Y Y Y I I P U A P A A A A A A A A A C A A A A A A A A A Z A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A A S }                                 ",
"                                                      J.i.u.t.G.                                  F.e.w.9.9.s.g.c.M.!./.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.^.^.^.^.^.).^.N.c.l.a.<.`             *. .X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.@.X.X.@.@.@.X.X.X.X.X...T T R R Y Y I I I P P P P P A A A A A A A A A A A A A A A A A A A A A A A A A A A A A C A A A A A A A A A A A P P P I I I I I I I P P A A A A A A A A A A A A A A A A C 4.                              ",
"                                                          J.u.w.0.) ) 0.z.D.D.y.u.D.D.y.w.D.z.0.s.s.g.c.n.E.R.W.W.W.Q.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.(.E.c.k.1./ G.          *.O.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.@.@.@.@.@.@.@.@.@.X.X.X.X.......T T Y Y Y Y I I I P P P A A A A A A A A A Z A A A A A A A A A A A P P I R T ....X.X.@.@.X.@.@.@.X.X.X...T Y I P A A A A A A A A A A A S A                               ",
"                                                                  e.q.( 1.a.j.l.c.k.k.k.c.k.n.M.V.W.(.(./.`.)./.)./.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.).U.c.x.( )           j $.@.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.%.X.X.@.X.@.X.@.@.@.X.=.@.@.@.X.X.X.X.X...X.....T R Y Y Y Y I I P P P P P A A P Y T ..X.@.@.@.@.@.X.@.X.X.X.X.X.X.@.X.X.@.@.X.X...R I A A A A A A A A A A S }                             ",
"                                                                        S.z.( a.f.j.c.c.c.v.m.N.!.)./.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.(.m.k.a./ F.        0 d #.@.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.@.@.@.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.@.X.X.@.@.X.@.@.X.@.@.X.X.X.X.X.........X.X.X.@.%.X.X.X.X.X.X.X.X.X.X.X.X.@.@.@.X.X.X.X.X.X.@.X...Y P A A A A A A A A C                             ",
"                          u.w.e.t.r.y.              J.t.e.Z.F.            S.( 2.( a.g.c.k.k.c.m.!.^.^.^.^./.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.T.c.x./ e.        7 % r ;.#.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.-.;.;.-.#.-.-.;.;.#.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.X.@.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.-.;.;.-.#.#.#.;.;.-.@.X.X.X.X.X.X.Y A A A A A A A S ^                           ",
"                      u.' w.e.e.r.S.                P.z.<.1.( / ( ) ' z.h.k.k.k.k.k.k.c.b.N.~._.).)././.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.!.c.l.( 0.        7 < 2 r ;.@.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.#.>.#.I G y w w w t y Z T ;.>.@.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.#.>.#.Y V y w w w t y J R -.>.@.X.X.X.X.@...I A A A A A A P                           ",
"                      F.                      t.z.0.3.1.1.1.1.1.a.f.d.j.v.c.c.c.c.c.b.N.W.(.Q.T.E.U.Y.Q.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.!.^.^.^.^.^.(./.Q.b.l.1.)         l < 2 2 r ;.@.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.;.Y y a > < < < % % % < - , w V @.-.X.X.X.X.X.X.X.X.X.X.X.%.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.%.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.>...e q > - 2 % < 2 % < - : w F @.;.X.X.X.X.@.X.Y A A A A A A 4.                        ",
"    J.K.                                      Z.] <./ <.<.1.1.1.g.C.v.v.c.v.v.c.c.v.V.M.m.c.c.c.B.B.U./.`./.).).(.^.^.(.^.^./././.^./.(.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.).Q.b.l.1.0.        l < < 2 2 p #.X.X.X.X.X.X.X.X.X.X.X.X.@.-.X.t : 2 2 2 2 2 3 3 3 3 2 2 2 2 = q G -.#.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.#.@.e : < 2 2 2 3 3 3 3 2 2 2 2 < = $ D -.#.X.X.X.X.@...P A A A A ~                         ",
"                                          F.e.w.A.S.Z.q.3.2.a.x.g.d.d.a.f.s.j.l.c.k.k.k.k.c.k.c.b.R.(.Q.W.Y.N.N.M.m.m.!.).(.^.Q.Q.^.Q.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.T.c.l.<.w.        l < < 3 3 2 p #.X.X.X.X.X.X.X.X.X.X.@.;.Z $ < 2 2 3 2 3 3 4 3 3 4 3 3 3 3 2 % = w ..;.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.;.P $ 2 2 2 3 2 3 3 3 4 3 4 3 3 3 2 2 2 % q T ;.@.X.X.X.@...P A A A A                         ",
"                                      J.t.t.                S.) / ` ) ) _ ( 1.a.a.1.( s.v.c.c.c.N.V.b.b.c.c.k.c.c.h.m.W.E.m.b.b.b.M.M.U.Y.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^./.(.M.k.j.( r.        l < 3 3 2 2 g @.X.X.X.X.X.X.X.X.X.@.;.y = 2 3 3 < 3 4 < = O O O + = < 4 3 3 3 3 % $ P ;.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.>.F - 2 3 3 3 3 4 < * O O O O = 3 3 3 < < 4 & # Z >.X.X.X.X.@.X.P A A A                         ",
"                                                              F.          F.1.1.1.1.a.l.v.v.c.c.c.l.k.c.c.c.c.v.c.b.E.b.c.M.E.W.Q.Q.!.!.!.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.).T.c.c.a./ S.        l < 3 3 3 2 g #.X.X.X.X.X.X.X.X.@.;.e & 2 3 3 3 4 = . X * 6 8 8 6 * . X 3 3 3 3 3 2 : K ;.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.%.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.%.X.X.X.X.X.X.X.X.X.X.X.;.y = 2 3 3 3 4 = . . ; 6 8 8 6 * X X < 4 4 < 4 < @ Z ;.X.X.X.X.@...A A C                         ",
"                                                                          t.<.<.( a.d.d.f.a.a.a.a.a.s.k.k.j.d.g.d.k.c.k.V.W.T.T.T.Q.).).`.^.(.^.^.^.^.^.^.^.^.^.^.^.^.^.`.!.b.c.g.1.)           l < 3 3 < 2 s #.X.X.X.X.X.X.X.X.;.e < 2 3 3 3 = . * b .X:X4X7X7X5X+XN x o O 3 3 3 3 % : I -.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.;.u = 2 4 3 3 3 X O c .X>X4X9X7X5X+XN x X O 4 < < 4 % @ P -.X.X.X.X.X.T A S |                       ",
"            p.p.                          u.r.                          A.] ( q.Z.Z.t.Z.e.e.t.z.<.<.1.a.( ) S.z.( k.c.c.b.c.k.s.9.9.c.M.W.^./././.^.^.^.^.^.^.^.^.^././.W.b.c.k.2./ u.          l < 2 3 3 2 s -.X.X.X.X.X.X.X.;.V = 2 3 3 4 = . b 5X0XqX7X5X5X5X4X9XqX0XOX6 o 3 4 2 3 2 a X.#.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.-.A = 2 3 3 3 = o c 6X0XqX7X4X5X5X4X9XqXwXOX9 . < 4 3 3 2 $ T @.X.X.X.X.@.Y S }                       ",
"        J.r.w.w.w.t.                    J.i.                          F._ e.                  A./ ( ) q.r.    ) f.v.v.v.j.a./ _ z.) x.k.c.m.E.Q.^.).).^./.`.).).).^.W.N.c.c.j.1./ e.            k < < 3 3 2 s -.X.X.X.X.X.X.@...$ % 3 3 4 O * .XtX5X3X1X6X6X6X6X:X1X6X6X9XwXb o < 4 3 3 % e ;.@.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.@.q 2 3 2 4 + X B tX4X6X6X6X:X6X6X6X6X3X3X9XeXn o < 3 3 3 % w >.X.X.X.X.X.@.U }                       ",
"                                                                      t.                    i.e.S.F.        0.d.l.j.f.1./ _ e.  P.) l.v.c.k.c.c.b.m.N.U.Y.E.Y.N.N.n.c.v.k.g.( / e.              k < 3 3 2 2 d -.X.X.X.X.X.X.;.t 2 1 3 3 O * OXeX:X6X6X6X3X3X3X5X3X3X6X6X6X5XuXb o 3 3 3 2 @ I @.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.,.y % 2 ; 4 = .  XtX:X6X6X3X3X5X3X5X3X6X3X1X:X3XuXM o 2 3 3 < = A ;.X.X.X.X.X...!                       ",
"                                                                                                        Z./ / 1.1./ ) ` A.      e.a.v.v.c.v.v.k.c.k.c.c.v.c.c.c.c.l.l.g.a./ / t.                l = 3 3 3 2 d ;...X.X.X.X.@.T @ 2 3 3 < X .XyX:X6X6X3X5X1X<X=X-X:X1X3X:X6X:X5XuXx . 3 3 3 % w ;.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.%.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.#.T , 2 3 3 3 o B tX:X6X6X3X3X6X<X-X-X<X3X5X:X6X:X6XuXc X 4 3 3 2 q -.@.X.X.X.X. .^                       ",
"                                                                                                    P.t.e.S.  G.u.P.            1.j.g.s.1.a.a.a.s.d.d.d.d.d.d.a.a.a.<./ / e.                    k & 3 3 3 2 d ;.X.X.X.X.X.;.e 2 3 3 4 X b uX:X:X6X3X1X*XoX{.[.[.|.@X-X5X6X6X:X9X5X* = 3 3 2 : T X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.;.u < 2 3 4 . x tX2X6X6X3X6X*XoX{.[.[.{.XX-X3X3X3X2X4XqX; O 3 3 2 - W -.X.X.X.X.X.*.                      ",
"                                                                                                                              q.( z.q.e.q.e.q.q.0.' ` ) ) ( / ) _ ) z.t.                        l < 3 3 3 2 r ;.X.X.X.X.X.#.a 2 3 3 < @ 5X5X:X6X5X1X@X'.'.'.'.'.'.'.{.*X3X3X6X:XtXM . 3 < 3 % u -.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.#.q 2 3 4 = O >X9X2X6X3X2X$X].'.'.'.'.'.'.[.*X2X3X6X6XwXN . < 3 3 & e -.X.X.X.X.X.*.                      ",
"                                                                                                                              Z.                                                              3 3 3 3 3 < 2 f ,.X.X.X...-.I @ 4 3 4 . b eX<X6X6X2X@X'.'.'.'.'.].'.'.'.[.-X3X6X6X5X4XO < 3 2 < w ;.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.#.T : 2 3 3 X x rX3X6X3X2X$X'.'.'.'.'.'.[.'.'.].*X3X3X6X4X4X; + 4 3 % q #.@.X.X.X. .*.                      ",
"                                                                                                                                                                                            < < < 3 3 3 3 2 r #.#.;.;.-.,.D = 2 3 3 O  X7X6X6X3X*X].'.'.'.'.'.'.'.'.'.'.|.:X3X3X:XeXx O 4 3 2 $ @.@.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.#.K < 2 3 < X N rX:X2X5X-X[.'.'.'.'.'.'.'.'.'.'.|.<X3X6X6XeXc O 3 3 2 : T @.X.X.X.$.5.                      ",
"                                                                                                                                                                                          4 < 3 3 3 3 < 3 3 1 $ s r i J @.t < 3 3 < + 3X5X6X3X1XoX'.'.'.'.'.'.'.].'.'.'.].*X3X2X:X0XM X 4 3 2 > Y #...X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.#.u < 3 3 = * +X0X:X3X2X|.'.'.'.'.'.'.'.'.'.'.'.].&X5X6X6XeXN . < 3 2 - I #.X.X.X.$.5.                      ",
"                                                                                                                                                                                          3 3 3 3 3 3 3 3 3 2 2 3 2 2 1 5 @ 1 2 4 + 6 9X3X2X3X<X{.'.'.'.'.'.'.'.'.'.'.'.'.@X2X6X6X9X.Xo 4 3 2 - E ;...X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.-.e % 3 3 = ; 3X4X6X3X2X|.N ].'.'.[.'.'.[.'.'.'.'.XX2X6X:X0X.XX < 3 3 = J #.X.X.X.X.5.                      ",
"                                                                                                                                                                                          z = 3 3 1 3 3 3 3 3 3 3 3 2 3 3 = 2 3 4 O 8 9X3X3X3X,X}.'.'.'.].'.].'.'.'.'.'.'.XX2X2X6X4X X. 3 3 3 - K -.X.X.X.X.X.X.X...X.X.X.X.X.X.X...X.X...X.X.X.X...X.X...X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.@.X...X.X.X.X...X.X.X.X...X.X.X.X.#.t 2 3 3 + ; 4X4X6X3X,X|.'.'.'.'.'.'.'.'.'.'.'.'.oX1X5X:XqXOX* = 3 3 = V -.@.@.@.@.*.                      ",
"                                                                                                                                                                                            9 < = < < < < 3 3 3 3 3 2 2 3 = 1 3 3 O 6 9X5X6X3X>X{.B '.'.'.'.].'.'.'.'.'.'.@X3X6X6X9X X. 3 3 3 - W ,.#.#.-.-.-.;.#.-.-.-.-.-.-.;.;.-.-.;.;.-.-.;.-.;.;.;.;.;.;.;.;.;.-.;.;.;.;.;.;.;.;.;.;.;.;.;.;.>.;.>.;.>.;.;.;.;.;.>.;.>.,.y % < 3 = ; 4X4X3X3X<X|.'.'.'.'.].'.'.'.'.'.'.'.|.3X3X:X0X XO < 3 3 < P ,.;.;.-.;.8.                      ",
"                                                                                                                                                                                                z k 7 4 < < = < 3 3 2 1 3 = < 3 3 = ; 4X3X6X3X1XoX'.'.'.[.'.'.'.'.'.'.'.'.*X3X6X:XqXN . 4 3 2 - K ..W Y W Y W W I W W W W Q P Q E E E K Q K K K K K K J J K J J J J J G G J J G G G G G F G G F F F F H F H H H i H i i i i H w < 3 3 = * >X9X:X3X2X|.'.'.'.'.'.'.'.'.'.'.'.'.$X3X3X:XwXB O < 3 3 = q r d w d w h                       ",
"                                                                                                                                                                                                            k 9 4 3 < < < = = 3 3 < X +X4X1X6X5X$X].'.'.'.'.'.'.'.[.].'.}.;X3X3X:XeXc X 3 3 3 = > 5 5 5 5 5 5 5 > 5 5 5 5 5 1 5 1 1 1 5 1 1 1 1 1 4 1 1 1 1 1 3 3 3 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 2 2 3 2 2 3 2 2 2 2 2 3 2 < 3 3 < X .XrX:X:X5X&X].'.'.'.'.[.'.'.'.'.'.|.-X3X2X:XtXb O 3 3 2 @ % 2 2 2 % 2 2 < k                   ",
"                                                                                                                                                                                                                      z 7 7 = 3 3 4 . m rX:X6X3X<X{.'.'.'.'.'.'.'.'.'.].$X2X3X3X6X0X; = 3 3 3 = 2 2 2 < 3 3 2 3 2 2 2 2 2 2 2 2 2 2 2 2 2 3 2 3 2 2 2 3 2 2 2 2 2 2 2 2 2 3 < 2 < 2 2 2 3 < 2 3 2 3 2 3 3 2 3 < 2 3 < < 3 2 2 < = 3 3 3 X b eX6X:X3X1XoX'.'.'.'.'.'.[.'.'.[.XX2X3X3X5XqX8 + 3 3 < < < 3 2 2 3 3 3 3 = v                 ",
"                                                                                                                                                                                                                            4 3 3 3 + 6 eX:X2X2X3X-X{.'.'.'.'.'.'.B ].@X2X3X6X:XwX.X. 3 3 3 < = 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 < 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 = 3 3 3 + ; 7X4X6X6X3X,X|.'.'.'.'.'.'.B ].|.:X3X:X2X0XOXX = 3 3 < < 3 3 3 3 3 3 3 3 < 4                 ",
"                                                                                                                                                                                                                              < 3 3 3 o B wX:X:X3X3X,XoX[.'.'.'.].|.%X2X3X6X6X3XtX6 O 3 3 3 = < 3 3 3 3 3 3 3 3 3 < 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 < 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 < 3 3 3 3 3 3 3 < 3 3 3 3 3 3 3 3 3 3 3 3 < < 3 3 3 . m wX:X3X6X3X,XXX[.'.'.].'.|.$X:X3X6X3X2XeXx X 3 3 3 = < 3 < 3 3 3 3 3 3 < 4                 ",
"                                                                                                                                                                                                                              3 3 3 3 = * 4X9X:X6X3X3X1X,X&X$X$X-X<X3X3X6X:X:XuXM . 3 3 3 3 = 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 2 3 3 3 2 3 3 < 3 3 3 3 3 3 3 3 3 3 3 < < 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 = 3 3 4 = X :X9X:X3X1X3X3X-X&X$X$X*X<X3X3X3X6X:XwXB . 2 3 3 3 @ < 3 2 3 3 3 3 3 3 = v                 ",
"                                                                                                                                                                                                                              k = 3 3 3 X 8 wX8X1X6X6X3X5X3X3X6X2X3X3X6X6X6XeX XX = 3 3 3 = = 4 3 4 3 3 3 3 4 3 3 4 3 1 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 < = = < = = < < = < = < < = = = < = = = = < = = 3 3 3 4 O 6 qX9X:X6X6X6X5X3X6X3X3X3X3X3X:X3XrX+XX = 4 3 3 = & < 3 3 3 3 3 < < < 9                   ",
"                                                                                                                                                                                                                                < < 3 3 < o x qXrX3X:X:X6X6X6X6X3X3X6X:X4XyX.XX O 4 3 3 = 9                                                                                                                                         3 = 3 3 3 . 6 7XwX5X:X:X2X3X3X6X6X6X3X:X5XtXOX* O 4 3 3 < 3                                         ",
"                                                                                                                                                                                                                                  = 3 3 3 3 . 6 OXwX0X5X:X:X:X:X:X:X7XeX9Xn X = 4 3 3 = 7                                                                                                                                             = 3 3 3 4 . ; .XeXwX5X:X:X:X:X:X:X4XeX0Xm . O 2 3 3 < ;                                           ",
"                                                                                                                                                                                                                                  x = 3 3 3 3 O X v  XqXyXeXwXwXtXeX:Xm 6 o = 4 3 3 < =                                                                                                                                                 < < < 3 3 O . x .X9XtXeXeXeXeXtX5XN 7 o = 4 3 3 < =                                             ",
"                                                                                                                                                                                                                                    3 = 3 3 3 4 = O O ; v n m M b 8 * X O 3 3 3 3 < 3                                                                                                                                                   l = 3 3 3 4 < O X ; x n M m b 8 ; X O 3 3 3 3 < =                                               ",
"                                                                                                                                                                                                                                      7 < < 3 3 3 3 = = O O X O O + < 2 3 3 3 3 < =                                                                                                                                                       k < < 3 3 3 4 3 = O X X O O + = < 3 3 3 3 < =                                                 ",
"                                                                                                                                                                                                                                          < = 3 3 3 3 3 3 3 3 3 3 3 3 ; 3 3 3 = 7                                                                                                                                                             < = 3 3 3 3 3 3 3 3 < 3 3 3 < 3 3 3 = 3                                                   ",
"                                                                                                                                                                                                                                            7 = < < 3 3 3 3 3 3 < 3 3 3 3 = 3                                                                                                                                                                   7 3 = < 3 3 3 3 3 3 3 3 4 3 - < =                                                       ",
"                                                                                                                                                                                                                                                8 < = < 3 < 3 < < < = = 4                                                                                                                                                                           9 3 = = < 3 < < < < = < 3                                                           ",
"                                                                                                                                                                                                                                                      k 6 4 3 4 7 7                                                                                                                                                                                         7 4 3 4 7 7                                                                 ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ",
"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "
};
