
/** Menu **/
#include "menu.h"
#include "menu_single.h"
#include "menu_multi.h"
#include "menu_rules.h"
#include "menu_leave.h"
#include "pause_menu.h"
#include "pause_menu_resume.h"
#include "pause_menu_exit.h"
#include "game_background.h"
#include "win.h"
#include "exit.h"
#include "regras.h"

/** Objects **/
#include "red_car.h"
#include "mouse_cursor.h"
#include "next.h"
#include "upp.h"


/** Letters **/
#include "letters/lower/a.h"
#include "letters/lower/b.h"
#include "letters/lower/c.h"
#include "letters/lower/d.h"
#include "letters/lower/e.h"
#include "letters/lower/f.h"
#include "letters/lower/g.h"
#include "letters/lower/h.h"
#include "letters/lower/i.h"
#include "letters/lower/j.h"
#include "letters/lower/k.h"
#include "letters/lower/l.h"
#include "letters/lower/m.h"
#include "letters/lower/n.h"
#include "letters/lower/o.h"
#include "letters/lower/p.h"
#include "letters/lower/q.h"
#include "letters/lower/r.h"
#include "letters/lower/s.h"
#include "letters/lower/t.h"
#include "letters/lower/u.h"
#include "letters/lower/v.h"
#include "letters/lower/w.h"
#include "letters/lower/x.h"
#include "letters/lower/y.h"
#include "letters/lower/z.h"

#include "letters/upper/A.h"
#include "letters/upper/B.h"
#include "letters/upper/C.h"
#include "letters/upper/D.h"
#include "letters/upper/E.h"
#include "letters/upper/F.h"
#include "letters/upper/G.h"
#include "letters/upper/H.h"
#include "letters/upper/I.h"
#include "letters/upper/J.h"
#include "letters/upper/K.h"
#include "letters/upper/L.h"
#include "letters/upper/M.h"
#include "letters/upper/N.h"
#include "letters/upper/O.h"
#include "letters/upper/P.h"
#include "letters/upper/Q.h"
#include "letters/upper/R.h"
#include "letters/upper/S.h"
#include "letters/upper/T.h"
#include "letters/upper/U.h"
#include "letters/upper/V.h"
#include "letters/upper/W.h"
#include "letters/upper/X.h"
#include "letters/upper/Y.h"
#include "letters/upper/Z.h"

/** Symbols **/

#include "symbols/apostrofe.h"
#include "symbols/doispontos.h"
#include "symbols/espaco.h"
#include "symbols/ponto.h"
#include "symbols/pontoexclamacao.h"
#include "symbols/pontointerrogacao.h"
#include "symbols/pontovirgula.h"
#include "symbols/traco.h"
#include "symbols/virgula.h"

/** Leaderboard **/

